source 'https://cdn.cocoapods.org/'

platform :ios, '9.0'
install! 'cocoapods',
deterministic_uuids: false,
disable_input_output_paths: true,
generate_multiple_pod_projects: true
incremental_installation: true

target 'MLSLoggerDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'MLSLogger', :path => '../'

end
